#define SERVOMIN  100
#define SERVOMAX  600
#define SERVO_NUM_SHOULDER_FR 0
#define SAFE_ANGLE_SHOULDER_FR 120
#define CLOSE_ANGLE_SHOULDER_FR 100
#define OPEN_ANGLE_SHOULDER_FR 15
#define MIDDLE_ANGLE_SHOULDER_FR 50

#define SERVO_NUM_SHOULDER_FL 4
#define SAFE_ANGLE_SHOULDER_FL 120
#define CLOSE_ANGLE_SHOULDER_FL 0
#define OPEN_ANGLE_SHOULDER_FL 85
#define MIDDLE_ANGLE_SHOULDER_FL 50

#define SERVO_NUM_SHOULDER_RR 15
#define SAFE_ANGLE_SHOULDER_RR 120
#define CLOSE_ANGLE_SHOULDER_RR 0
#define OPEN_ANGLE_SHOULDER_RR 85
#define MIDDLE_ANGLE_SHOULDER_RR 50

#define SERVO_NUM_SHOULDER_RL 11
#define SAFE_ANGLE_SHOULDER_RL 120
#define CLOSE_ANGLE_SHOULDER_RL 100
#define OPEN_ANGLE_SHOULDER_RL 15
#define MIDDLE_ANGLE_SHOULDER_RL 50