#ifndef CONFIG_H
#define CONFIG_H

#define SERVOMIN  100
#define SERVOMAX  600
#define SERVO_NUM_SHOULDER_FR 0
#define SAFE_ANGLE_SHOULDER_FR 120
#define CLOSE_ANGLE_SHOULDER_FR 100
#define OPEN_ANGLE_SHOULDER_FR 22
#define MIDDLE_ANGLE_SHOULDER_FR ((CLOSE_ANGLE_SHOULDER_FR + OPEN_ANGLE_SHOULDER_FR)/2)

#define SERVO_NUM_SHOULDER_FL 4
#define SAFE_ANGLE_SHOULDER_FL 120
#define CLOSE_ANGLE_SHOULDER_FL 0
#define OPEN_ANGLE_SHOULDER_FL 78
#define MIDDLE_ANGLE_SHOULDER_FL ((CLOSE_ANGLE_SHOULDER_FL + OPEN_ANGLE_SHOULDER_FL)/2)

#define SERVO_NUM_SHOULDER_RR 15
#define SAFE_ANGLE_SHOULDER_RR 120
#define CLOSE_ANGLE_SHOULDER_RR 0
#define OPEN_ANGLE_SHOULDER_RR 78
#define MIDDLE_ANGLE_SHOULDER_RR ((CLOSE_ANGLE_SHOULDER_RR + OPEN_ANGLE_SHOULDER_RR)/2)

#define SERVO_NUM_SHOULDER_RL 11
#define SAFE_ANGLE_SHOULDER_RL 120
#define CLOSE_ANGLE_SHOULDER_RL 100
#define OPEN_ANGLE_SHOULDER_RL 27
#define MIDDLE_ANGLE_SHOULDER_RL ((CLOSE_ANGLE_SHOULDER_RL + OPEN_ANGLE_SHOULDER_RL)/2)

#define SERVO_NUM_ARM_FR 6
#define SAFE_MAX_ANGLE_ARM_FR 180
#define SAFE_MIN_ANGLE_ARM_FR 5
#define CLOSE_ANGLE_ARM_FR 180
#define STAND_ANGLE_ARM_FR 90
#define RAISE_ANGLE_ARM_FR 0

#define SERVO_NUM_ARM_RL 13
#define SAFE_MAX_ANGLE_ARM_RL 175
#define SAFE_MIN_ANGLE_ARM_RL 5
#define CLOSE_ANGLE_ARM_RL 175
#define STAND_ANGLE_ARM_RL 90
#define RAISE_ANGLE_ARM_RL 0

#define SERVO_NUM_ARM_FL 2
#define SAFE_MIN_ANGLE_ARM_FL 0
#define SAFE_MAX_ANGLE_ARM_FL 180
#define CLOSE_ANGLE_ARM_FL 5
#define STAND_ANGLE_ARM_FL 90
#define RAISE_ANGLE_ARM_FL 180

#define SERVO_NUM_ARM_RR 9
#define SAFE_MIN_ANGLE_ARM_RR 0
#define SAFE_MAX_ANGLE_ARM_RR 180
#define CLOSE_ANGLE_ARM_RR 5
#define STAND_ANGLE_ARM_RR 90
#define RAISE_ANGLE_ARM_RR 180

#define MOTOR_FR_IN1	26
#define MOTOR_FR_IN2	25
#define MOTOR_RR_IN3	33
#define MOTOR_RR_IN4	32

#define MOTOR_RL_IN1    4
#define MOTOR_RL_IN2    16
#define MOTOR_FL_IN3	17
#define MOTOR_FL_IN4	5

#define MAX_SPEED 255 //từ 0-255
#define MIN_SPEED 0

#endif
